### ISSUE TITLE
Issue creating a new session if no classes added

### ISSUE THREAD

**Issue by jmj6ry** [uva-cs3240-s22/group-project-b-12#22]
If the user first signs in and doesn't have any classes added to their profile, an error happens when trying to add a session. "RelatedObjectDoesNotExist at /sessions/submit/ ... User has no profile." 
We might want to have a conditional somewhere to check for this or redirect new users to the profile page so that they can add classes before going to main page.

**Comment by nesa7** [comment]
Fixed in "newSessionBugFix" branch. The page now redirects users to add courses to their profile when they try to add a session without having any courses added.
